spring.application.name=banking-platform

spring.datasource.url=jdbc:postgresql://localhost:5432/banking_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

bank.security.jwt.secret=AX6YWjj+/8G0gg3DVU2wvYh837Alv+CMjsuxT9l0qPk=
bank.security.jwt.expiration= 86400000